/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_android_mqttjnidemo2_Hello */

#ifndef _Included_com_example_android_mqttjnidemo2_Hello
#define _Included_com_example_android_mqttjnidemo2_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_android_mqttjnidemo2_Hello
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_android_mqttjnidemo2_Hello_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_android_mqttjnidemo2_Hello
 * Method:    subscribe
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_android_mqttjnidemo2_Hello_subscribe
  (JNIEnv *, jobject);

/*
 * Class:     com_example_android_mqttjnidemo2_Hello
 * Method:    reconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_android_mqttjnidemo2_Hello_reconnect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
